# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 719cd8c5285536da26843a1f262eae7bfa4524c20dd6d0130addc83e81c886d63a1fabd1ebd1dad05447565d0d591d5d31610ce0b68a5cf376cf54f1cc00df87

test:
  secret_key_base: 35369498f60f27496e84b80bdd94510af8a3a2202ccb031a08904a642c7f39b2f2ce0dfd1d9a3d22f1d493cb9855440d097284c07371ef0508c571af21640176

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
